{{- if not .Values.secretRefs.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $k, $v := .Values.secretRefs.env }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
